config/routes.rb
Rails.application.routes.draw do

  resources :tbl_place_holder_contents

  resources :tbl_layout_placeholders

  resources :tbl_place_holders

  resources :tbl_globals

  resources :tbl_form_field_helpers

  resources :tbl_configs

  resources :tbl_banner_media

  resources :tbl_page_forms

  resources :tbl_form_fields

  resources :tbl_forms

  resources :tbl_media

  resources :tbl_banners

  resources :tbl_page_banners

  resources :tbl_pic_settings

  resources :tbl_page_categories

  resources :tbl_categories

  resources :tbl_page_contents

  resources :tbl_contents

  resources :tbl_pages

  resources :tbl_layouts

  resources :tbl_logins

  get 'tbl_contents/new/:id' => 'tbl_contents#new', as: :zzz
  get 'place_holder_news/index' => 'place_holder_new#index', as: :ada
  get 'tbl_contents/:id/edit/:id' => 'tbl_contents#edit', as: :editcontent

  get "log_out" => "cms#logout", :as => "log_out"

  get 'myaccount' => 'cms#myaccount', :as => 'myaccount'

  get '/tbl_place_holders/new/:id' => 'tbl_place_holders#new' , as: :newplaceholder

  get 'edit/:id' => 'tbl_layouts#edit', as: :editlayout

  get ':id/edit/:id' => 'tbl_pages#edit', as: :edit

  get '/tbl_contents/new/:id' => 'tbl_contents#new' , as: :new
  get '/tbl_banners/new/:id' => 'tbl_banners#new' , as: :newbanner

  get 'cm/cm'

 @pageinfo=TblPage.all
 @pageinfo.each do |index|

    @LayoutID=index.LayoutID
    @PageTitle=index.PageTitle
    @PageID=index.PageID
    @Status=index.Status

 @layoutinfo=TblLayout.where(LayoutID: @LayoutID)

    @layoutinfo.each do |index|

         @OnStateTag=index.OnStateTag

            if @OnStateTag == "FW"
                  get 'FW/'+@PageTitle+'/:id' =>'vol#Volunteers'
            end

            if @OnStateTag == "H"
              get 'H/'+@PageTitle+'/:id' => 'home#Home'
            end

            if @OnStateTag == "A"
              get 'A/'+@PageTitle+'/:id' => 'about_us#AboutUs'
            end

            if @OnStateTag == "AL"
              get 'AL/'+ @PageTitle+'/:id' => 'al_orthodontics#Orthodontics'
            end
         if @OnStateTag == "C"
             get 'C'+'/'+ @PageTitle+'/:id' => 'contact_us#ContactUs'
         end
          if @OnStateTag == "FQ"

            get 'FQ'+'/'+ @PageTitle+'/:id' => 'faq#Faq'
          end

      end
    end

  root 'home#Home'

  resources :tbl_cms
    post 'cm/processlogin'

resources :cms do
  collection do
    get 'index'
  end
  post 'processlogin', :on => :collection
end

end

app/models/tbl_place_holder.rb
class TblPlaceHolder < ActiveRecord::Base
end

app/controllers/tbl_place_holders_controller.rb
class TblPlaceHoldersController < ApplicationController
  before_action :set_tbl_place_holder, only: [:show, :edit, :update, :destroy]

  # GET /tbl_place_holders
  # GET /tbl_place_holders.json
  def index
    @tbl_place_holders = TblPlaceHolder.all
    session[:placeholderdeleted] = 0
  end

  # GET /tbl_place_holders/1
  # GET /tbl_place_holders/1.json
  def show
  end

  # GET /tbl_place_holders/new
  def new
    @tbl_place_holder = TblPlaceHolder.new
    if params[:id] == nil
      session[:decision_placeholder]=0
    else

      session[:layoutID]=params[:id]
      session[:decision_placeholder]=1
    end
  end

  # GET /tbl_place_holders/1/edit
  def edit
    if params[:id] != nil
    @place=TblPlaceHolder.find_by_PlaceHolderID(params[:id])
    @placeTitle=@place.Type
      end
  end

  # POST /tbl_place_holders
  # POST /tbl_place_holders.json
  def create
    @tbl_place_holder = TblPlaceHolder.new(tbl_place_holder_params)

    respond_to do |format|
      if @tbl_place_holder.save
        format.html { redirect_to @tbl_place_holder, notice: 'Tbl place holder was successfully created.' }

        @querylast=  TblPlaceHolder.last()

        @placeholderID_last=@querylast.PlaceHolderID

        if params[:id] = @placeholderID_last
          if session[:decision_placeholder] == 1
            query="INSERT INTO tbl_layout_placeholders (PlaceHolderID,LayoutID) values (#{@placeholderID_last},#{session[:layoutID]});"

            ActiveRecord::Base.connection.execute(query);
          end
        end

        if session[:placeholderdeleted] == 0
            if params[:placehold_hid] == ""
                  @placeholdinfo=TblPlaceHolder.first
                  @placeholdid=@placeholdinfo.PlaceHolderID
                  params[:placehold_hid]=@placeholdid
            end
            @placeinfo=TblPlaceHolder.find_by_PlaceHolderID(params[:placehold_hid])
            @placetype=@placeinfo.Type
          query="UPDATE tbl_place_holders SET Type='#{@placetype}' where PlaceHolderID=#{@placeholderID_last};"
            ActiveRecord::Base.connection.execute(query);
        end

        format.json { render :show, status: :created, location: @tbl_place_holder }
      else
        format.html { render :new }
        format.json { render json: @tbl_place_holder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tbl_place_holders/1
  # PATCH/PUT /tbl_place_holders/1.json
  def update
    respond_to do |format|
      if @tbl_place_holder.update(tbl_place_holder_params)

        if session[:placeholderdeleted] == 0


          if params[:placehold_hid] == ""
            @placeholdinfo=TblPlaceHolder.find_by_PlaceHolderID(params[:id])
            @placeholdid=@placeholdinfo.PlaceHolderID
            params[:placehold_hid]=@placeholdid
          end

          @placeinfo=TblPlaceHolder.find_by_PlaceHolderID(params[:placehold_hid])
          @placetype=@placeinfo.Type

          query="UPDATE tbl_place_holders SET Type='#{@placetype}' where PlaceHolderID=#{params[:id]};"
          ActiveRecord::Base.connection.execute(query);

        end

        format.html { redirect_to @tbl_place_holder, notice: 'Tbl place holder was successfully updated.' }
        format.json { render :show, status: :ok, location: @tbl_place_holder }
      else
        format.html { render :edit }
        format.json { render json: @tbl_place_holder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tbl_place_holders/1
  # DELETE /tbl_place_holders/1.json
  def destroy
    #whenever delete button is pressed from edit page only entry is deleted from
    #bridge table

    if params[:id] != nil
      if  session[:placeholderdeleted] == 1
        query = "DELETE FROM tbl_layout_placeholders where LayoutID =#{session[:layoutID]} and PlaceHolderID =#{params[:id]};"

        ActiveRecord::Base.connection.execute(query);
      end
    end

    #whenever delete button is pressed from PlaceHolder index page entry is deleted from Placeholder table as well
    #as from the bridge table

    if session[:placeholderdeleted] == 0

      query = "DELETE FROM tbl_layout_placeholders where LayoutID =#{session[:layoutID]} and PlaceHolderID =#{params[:id]};"

      ActiveRecord::Base.connection.execute(query);
      @tbl_place_holder.destroy

    end

    respond_to do |format|
      format.html { redirect_to tbl_place_holders_url, notice: 'Tbl place holder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tbl_place_holder
      @tbl_place_holder = TblPlaceHolder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tbl_place_holder_params
      params.require(:tbl_place_holder).permit(:PlaceHolderID, :PlaceHolderTitle, :PlaceHolderDesc, :IsActive,:Type)
    end

end

app/helpers/tbl_place_holders_helper.rb
module TblPlaceHoldersHelper
end

app/views/tbl_place_holders/_form.html.erb
<div class="external">
<%= form_for(@tbl_place_holder) do |f| %>
  <% if @tbl_place_holder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tbl_place_holder.errors.count, "error") %> prohibited this tbl_place_holder from being saved:</h2>

      <ul>
      <% @tbl_place_holder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :PlaceHolderTitle %><br>
    <%= f.text_field :PlaceHolderTitle %>
  </div>
      <div class="field">
        <%= f.label :PlaceHolderType %><br>

        <%= collection_select(:TblPlaceHolder, :PlaceHolderID, TblPlaceHolder.find_by_sql(" SELECT Type,PlaceHolderID FROM tbl_place_holders GROUP by Type order by PlaceHolderID; "), :PlaceHolderID, :Type , {:selected => TblPlaceHolder.where(Type: @placeTitle).map(&:PlaceHolderID)} )%>
      </div>
      <script type="text/javascript">

          $('#TblPlaceHolder_PlaceHolderID').on('change', function() {
              var id=$(this).val()
              $("#hidfield").val(id);

          });

      </script>
      <input type="hidden" id="hidfield" name="placehold_hid"  />
  <div class="field">
    <%= f.label :PlaceHolderDesc %><br>
    <%= f.text_field :PlaceHolderDesc %>
  </div>
  <div class="field">
    <%= f.label :IsActive %><br>
    <%= f.check_box :IsActive %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn_submit"%>
  </div>
<% end %>
</div>

app/views/tbl_place_holders/edit.html.erb
<h1 class="edit1">Edit PlaceHolder</h1>
<script type="text/javascript">
    $(document).ready(function(){
        $("#placeholder").css("background-color", "red");

    });
</script>
<%= render 'form' %>
<div class="edit2">
<%= link_to 'View', @tbl_place_holder , :class => "btn_submit"%> |
<%= link_to 'Back', tbl_place_holders_path, :class => "btn_submit" %>
</div>

app/views/tbl_place_holders/index.html.erb
<h1 class="index1">PlaceHolder Management</h1>
<script type="text/javascript">
    $(document).ready(function(){
        $("#placeholder").css("background-color", "red");

    });
</script>

<div class="index3">
  <%= link_to 'Add New PlaceHolder', new_tbl_place_holder_path, :class => "btn_submit" %>
</div>

<table class="index2">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Type</th>
      <th>Placeholderdesc</th>
      <th>Isactive</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tbl_place_holders.each do |tbl_place_holder| %>
      <tr>
        <td><%= tbl_place_holder.PlaceHolderID %></td>
        <td><%= tbl_place_holder.PlaceHolderTitle %></td>
        <td><%= tbl_place_holder.Type %></td>

        <td><%= tbl_place_holder.PlaceHolderDesc %></td>
        <td><%= tbl_place_holder.IsActive %></td>
        <td id="viewitem"><%= link_to 'View', tbl_place_holder %></td>
        <td id="edititem"><%= link_to 'Edit', edit_tbl_place_holder_path(tbl_place_holder) %></td>
        <td id="deleteitem"><%= link_to 'Delete', tbl_place_holder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<!--<style type="text/css">
    #viewitem  a {
        position: relative;
        right: -5px;

    }
    #edititem  a {
        position: relative;
        right: -15px;

    }
    #deleteitem  a {
        position: relative;
        right: -26px;

    }
</style>-->

app/views/tbl_place_holders/new.html.erb
<h1 class="new1">Add New PlaceHolder</h1>

<%= render 'form' %>
<div class="new2">
<%= link_to 'Back', tbl_place_holders_path, :class => "btn_submit" %>
</div>

app/views/tbl_place_holders/show.html.erb
<h1  class="show1">PlaceHolder Information</h1>

<script type="text/javascript">
    $(document).ready(function(){
        $("#placeholder").css("background-color", "red");

    });
</script>

<div class="show2">

<p id="notice"><%= notice %></p>

<p>
  <strong>Placeholderid:</strong>
  <%= @tbl_place_holder.PlaceHolderID %>
</p>

<p>
  <strong>Placeholdertitle:</strong>
  <%= @tbl_place_holder.PlaceHolderTitle %>
</p>

<p>
  <strong>Placeholderdesc:</strong>
  <%= @tbl_place_holder.PlaceHolderDesc %>
</p>

<p>
  <strong>Isactive:</strong>
  <%= @tbl_place_holder.IsActive %>
</p>
</div>
<div class="show3">
<%= link_to 'View', edit_tbl_place_holder_path(@tbl_place_holder) , :class => "btn_submit"%> |
<%= link_to 'Back', tbl_place_holders_path, :class => "btn_submit" %>
</div>