config/routes.rb
Rails.application.routes.draw do

  resources :tbl_place_holder_contents

  resources :tbl_layout_placeholders

  resources :tbl_place_holders

  resources :tbl_globals

  resources :tbl_form_field_helpers

  resources :tbl_configs

  resources :tbl_banner_media

  resources :tbl_page_forms

  resources :tbl_form_fields

  resources :tbl_forms

  resources :tbl_media

  resources :tbl_banners

  resources :tbl_page_banners

  resources :tbl_pic_settings

  resources :tbl_page_categories

  resources :tbl_categories

  resources :tbl_page_contents

  resources :tbl_contents

  resources :tbl_pages

  resources :tbl_layouts

  resources :tbl_logins

  get 'tbl_contents/new/:id' => 'tbl_contents#new', as: :zzz
  get 'place_holder_news/index' => 'place_holder_new#index', as: :ada
  get 'tbl_contents/:id/edit/:id' => 'tbl_contents#edit', as: :editcontent

  get "log_out" => "cms#logout", :as => "log_out"

  get 'myaccount' => 'cms#myaccount', :as => 'myaccount'

  get '/tbl_place_holders/new/:id' => 'tbl_place_holders#new' , as: :newplaceholder

  get 'edit/:id' => 'tbl_layouts#edit', as: :editlayout

  get ':id/edit/:id' => 'tbl_pages#edit', as: :edit

  get '/tbl_contents/new/:id' => 'tbl_contents#new' , as: :new
  get '/tbl_banners/new/:id' => 'tbl_banners#new' , as: :newbanner

  get 'cm/cm'

 @pageinfo=TblPage.all
 @pageinfo.each do |index|

    @LayoutID=index.LayoutID
    @PageTitle=index.PageTitle
    @PageID=index.PageID
    @Status=index.Status

 @layoutinfo=TblLayout.where(LayoutID: @LayoutID)

    @layoutinfo.each do |index|

         @OnStateTag=index.OnStateTag

            if @OnStateTag == "FW"
                  get 'FW/'+@PageTitle+'/:id' =>'vol#Volunteers'
            end

            if @OnStateTag == "H"
              get 'H/'+@PageTitle+'/:id' => 'home#Home'
            end

            if @OnStateTag == "A"
              get 'A/'+@PageTitle+'/:id' => 'about_us#AboutUs'
            end

            if @OnStateTag == "AL"
              get 'AL/'+ @PageTitle+'/:id' => 'al_orthodontics#Orthodontics'
            end
         if @OnStateTag == "C"
             get 'C'+'/'+ @PageTitle+'/:id' => 'contact_us#ContactUs'
         end
          if @OnStateTag == "FQ"

            get 'FQ'+'/'+ @PageTitle+'/:id' => 'faq#Faq'
          end

      end
    end

  root 'home#Home'

  resources :tbl_cms
    post 'cm/processlogin'

resources :cms do
  collection do
    get 'index'
  end
  post 'processlogin', :on => :collection
end

end

app/models/cms.rb
class Cms < ActiveRecord::Base
  begin

    def self.authenticate(username="", password="")

      user = find_by_username(username)

      if user && user.password == password
        user
      else

        nil
      end

    end


  rescue

  ensure

  end
end

app/models/tbl_banner.rb
class TblBanner < ActiveRecord::Base
end

app/models/tbl_category.rb
class TblCategory < ActiveRecord::Base

end

app/models/tbl_cm.rb
class TblCm < ActiveRecord::Base
  begin
    def encrypt_password

      if password.present?

        self.password_salt = BCrypt::Engine.generate_salt

        self.password = BCrypt::Engine.hash_secret(password, password_salt)

      end

    end

    def self.authenticate(username="", password="")

      user = find_by_username(username)

      if user && user.password == BCrypt::Engine.hash_secret(password,user.password_salt)
        user
      else

        nil
      end

    end


  rescue

  ensure

  end
end

app/models/tbl_config.rb
class TblConfig < ActiveRecord::Base
end

app/models/tbl_content.rb
class TblContent < ActiveRecord::Base
end

app/models/tbl_form.rb
class TblForm < ActiveRecord::Base
end

app/models/tbl_form_field.rb
class TblFormField < ActiveRecord::Base
end

app/models/tbl_global.rb
class TblGlobal < ActiveRecord::Base
end

app/models/tbl_layout.rb
class TblLayout < ActiveRecord::Base
end

app/models/tbl_login.rb
class TblLogin < ActiveRecord::Base
end

app/models/tbl_medium.rb
class TblMedium < ActiveRecord::Base
end

app/models/tbl_page.rb
class TblPage < ActiveRecord::Base

end

app/models/tbl_page_banner.rb
class TblPageBanner < ActiveRecord::Base
end

app/models/tbl_page_category.rb
class TblPageCategory < ActiveRecord::Base
end

app/models/tbl_page_form.rb
class TblPageForm < ActiveRecord::Base
end

app/models/tbl_pic_setting.rb
class TblPicSetting < ActiveRecord::Base
end

app/controllers/tbl_page_categories_controller.rb
class TblPageCategoriesController < ApplicationController
  before_action :set_tbl_page_category, only: [:show, :edit, :update, :destroy]

  # GET /tbl_page_categories
  # GET /tbl_page_categories.json
  def index
    @tbl_page_categories = TblPageCategory.all

  end

  # GET /tbl_page_categories/1
  # GET /tbl_page_categories/1.json
  def show
  end

  # GET /tbl_page_categories/new
  def new
    @tbl_page_category = TblPageCategory.new
  end

  # GET /tbl_page_categories/1/edit
  def edit
  end

  # POST /tbl_page_categories
  # POST /tbl_page_categories.json
  def create
    @tbl_page_category = TblPageCategory.new(tbl_page_category_params)

    respond_to do |format|
      if @tbl_page_category.save
        format.html { redirect_to @tbl_page_category, notice: 'Tbl page category was successfully created.' }
        format.json { render :show, status: :created, location: @tbl_page_category }
      else
        format.html { render :new }
        format.json { render json: @tbl_page_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tbl_page_categories/1
  # PATCH/PUT /tbl_page_categories/1.json
  def update
    respond_to do |format|
      if @tbl_page_category.update(tbl_page_category_params)
        format.html { redirect_to @tbl_page_category, notice: 'Tbl page category was successfully updated.' }
        format.json { render :show, status: :ok, location: @tbl_page_category }
      else
        format.html { render :edit }
        format.json { render json: @tbl_page_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tbl_page_categories/1
  # DELETE /tbl_page_categories/1.json
  def destroy
    @tbl_page_category.destroy
    respond_to do |format|
      format.html { redirect_to tbl_page_categories_url, notice: 'Tbl page category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tbl_page_category
      @tbl_page_category = TblPageCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tbl_page_category_params
      params.require(:tbl_page_category).permit(:CategoryID, :PageID)
    end
end

app/helpers/cms_helper.rb
module CmsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tbl_page_categories_helper.rb
module TblPageCategoriesHelper
end

app/helpers/vol_helper.rb
module VolHelper
end

app/views/tbl_page_categories/_form.html.erb
<div class="external">
<%= form_for(@tbl_page_category) do |f| %>
  <% if @tbl_page_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tbl_page_category.errors.count, "error") %> prohibited this tbl_page_category from being saved:</h2>

      <ul>
      <% @tbl_page_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :CategoryID %><br>
    <%= f.number_field :CategoryID %>
  </div>
  <div class="field">
    <%= f.label :PageID %><br>
    <%= f.number_field :PageID %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn_submit" %>
  </div>
<% end %>
</div>

app/views/tbl_page_categories/edit.html.erb
<h1 class="edit1">Editing PageCategories</h1>
<script type="text/javascript">
    $(document).ready(function(){
        $("#categorymang").css("background-color", "red");

    });
</script>
<%= render 'form' %>
<div class="edit2">
<%= link_to 'View', @tbl_page_category, :class => "btn_submit" %> |
<%= link_to 'Back', tbl_page_categories_path, :class => "btn_submit" %>
</div>

app/views/tbl_page_categories/index.html.erb
<h1 class="index1">Page Categories Management</h1>

<div class="index3">
  <%= link_to 'Add New Page Category', new_tbl_page_category_path , :class => "btn_submit"%>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $("#categorymang").css("background-color", "red");

    });
</script>

<table class="index2">
  <thead>
    <tr>
      <th>Category ID</th>
      <th>Page ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tbl_page_categories.each do |tbl_page_category| %>
      <tr>
        <td><%= tbl_page_category.CategoryID %></td>
        <td><%= tbl_page_category.PageID %></td>
        <td id="viewitem"><%= link_to 'View', tbl_page_category %></td>
        <td id="edititem"><%= link_to 'Edit', edit_tbl_page_category_path(tbl_page_category) %></td>
        <td id="deleteitem"><%= link_to 'Delete', tbl_page_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!--<style type="text/css">
    #viewitem  a {
        position: relative;
        right: -5px;

    }
    #edititem  a {
        position: relative;
        right: -15px;

    }
    #deleteitem  a {
        position: relative;
        right: -26px;

    }
</style>-->

app/views/tbl_page_categories/new.html.erb
<h1 class="new1">Add New PageCategory</h1>
<script type="text/javascript">
    $(document).ready(function(){
        $("#categorymang").css("background-color", "red");

    });
</script>
<%= render 'form' %>
<div class="new2">
<%= link_to 'Back', tbl_page_categories_path , :class => "btn_submit"%>
</div>

app/views/tbl_page_categories/show.html.erb
<h1  class="show1">PageCategories Information</h1>
<script type="text/javascript">
    $(document).ready(function(){
        $("#categorymang").css("background-color", "red");

    });
</script>
<div class="show2">
<p id="notice"><%= notice %></p>

<p>
  <strong>Categoryid:</strong>
  <%= @tbl_page_category.CategoryID %>
</p>

<p>
  <strong>Pageid:</strong>
  <%= @tbl_page_category.PageID %>
</p>
</div>

<div class="show3">
<%= link_to 'Edit', edit_tbl_page_category_path(@tbl_page_category) , :class => "btn_submit"%> |
<%= link_to 'Back', tbl_page_categories_path, :class => "btn_submit" %>
</div>