config/routes.rb
Rails.application.routes.draw do

  resources :tbl_place_holder_contents

  resources :tbl_layout_placeholders

  resources :tbl_place_holders

  resources :tbl_globals

  resources :tbl_form_field_helpers

  resources :tbl_configs

  resources :tbl_banner_media

  resources :tbl_page_forms

  resources :tbl_form_fields

  resources :tbl_forms

  resources :tbl_media

  resources :tbl_banners

  resources :tbl_page_banners

  resources :tbl_pic_settings

  resources :tbl_page_categories

  resources :tbl_categories

  resources :tbl_page_contents

  resources :tbl_contents

  resources :tbl_pages

  resources :tbl_layouts

  resources :tbl_logins

  get 'tbl_contents/new/:id' => 'tbl_contents#new', as: :zzz
  get 'place_holder_news/index' => 'place_holder_new#index', as: :ada
  get 'tbl_contents/:id/edit/:id' => 'tbl_contents#edit', as: :editcontent

  get "log_out" => "cms#logout", :as => "log_out"

  get 'myaccount' => 'cms#myaccount', :as => 'myaccount'

  get '/tbl_place_holders/new/:id' => 'tbl_place_holders#new' , as: :newplaceholder

  get 'edit/:id' => 'tbl_layouts#edit', as: :editlayout

  get ':id/edit/:id' => 'tbl_pages#edit', as: :edit

  get '/tbl_contents/new/:id' => 'tbl_contents#new' , as: :new
  get '/tbl_banners/new/:id' => 'tbl_banners#new' , as: :newbanner

  get 'cm/cm'

 @pageinfo=TblPage.all
 @pageinfo.each do |index|

    @LayoutID=index.LayoutID
    @PageTitle=index.PageTitle
    @PageID=index.PageID
    @Status=index.Status

 @layoutinfo=TblLayout.where(LayoutID: @LayoutID)

    @layoutinfo.each do |index|

         @OnStateTag=index.OnStateTag

            if @OnStateTag == "FW"
                  get 'FW/'+@PageTitle+'/:id' =>'vol#Volunteers'
            end

            if @OnStateTag == "H"
              get 'H/'+@PageTitle+'/:id' => 'home#Home'
            end

            if @OnStateTag == "A"
              get 'A/'+@PageTitle+'/:id' => 'about_us#AboutUs'
            end

            if @OnStateTag == "AL"
              get 'AL/'+ @PageTitle+'/:id' => 'al_orthodontics#Orthodontics'
            end
         if @OnStateTag == "C"
             get 'C'+'/'+ @PageTitle+'/:id' => 'contact_us#ContactUs'
         end
          if @OnStateTag == "FQ"

            get 'FQ'+'/'+ @PageTitle+'/:id' => 'faq#Faq'
          end

      end
    end

  root 'home#Home'

  resources :tbl_cms
    post 'cm/processlogin'

resources :cms do
  collection do
    get 'index'
  end
  post 'processlogin', :on => :collection
end

end

app/models/cms.rb
class Cms < ActiveRecord::Base
  begin

    def self.authenticate(username="", password="")

      user = find_by_username(username)

      if user && user.password == password
        user
      else

        nil
      end

    end


  rescue

  ensure

  end
end

app/models/tbl_banner.rb
class TblBanner < ActiveRecord::Base
end

app/models/tbl_category.rb
class TblCategory < ActiveRecord::Base

end

app/models/tbl_cm.rb
class TblCm < ActiveRecord::Base
  begin
    def encrypt_password

      if password.present?

        self.password_salt = BCrypt::Engine.generate_salt

        self.password = BCrypt::Engine.hash_secret(password, password_salt)

      end

    end

    def self.authenticate(username="", password="")

      user = find_by_username(username)

      if user && user.password == BCrypt::Engine.hash_secret(password,user.password_salt)
        user
      else

        nil
      end

    end


  rescue

  ensure

  end
end

app/models/tbl_config.rb
class TblConfig < ActiveRecord::Base
end

app/models/tbl_content.rb
class TblContent < ActiveRecord::Base
end

app/models/tbl_form.rb
class TblForm < ActiveRecord::Base
end

app/models/tbl_form_field.rb
class TblFormField < ActiveRecord::Base
end

app/models/tbl_global.rb
class TblGlobal < ActiveRecord::Base
end

app/models/tbl_layout.rb
class TblLayout < ActiveRecord::Base
end

app/models/tbl_login.rb
class TblLogin < ActiveRecord::Base
end

app/models/tbl_medium.rb
class TblMedium < ActiveRecord::Base
end

app/models/tbl_page.rb
class TblPage < ActiveRecord::Base

end

app/models/tbl_page_banner.rb
class TblPageBanner < ActiveRecord::Base
end

app/models/tbl_page_form.rb
class TblPageForm < ActiveRecord::Base
end

app/models/tbl_pic_setting.rb
class TblPicSetting < ActiveRecord::Base
end

app/models/tbl_place_holder_content.rb
class TblPlaceHolderContent < ActiveRecord::Base
end

app/controllers/tbl_place_holder_contents_controller.rb
class TblPlaceHolderContentsController < ApplicationController
  before_action :set_tbl_place_holder_content, only: [:show, :edit, :update, :destroy]

  # GET /tbl_place_holder_contents
  # GET /tbl_place_holder_contents.json
  def index
    @tbl_place_holder_contents = TblPlaceHolderContent.all
  end

  # GET /tbl_place_holder_contents/1
  # GET /tbl_place_holder_contents/1.json
  def show
  end

  # GET /tbl_place_holder_contents/new
  def new
    @tbl_place_holder_content = TblPlaceHolderContent.new
  end

  # GET /tbl_place_holder_contents/1/edit
  def edit
  end

  # POST /tbl_place_holder_contents
  # POST /tbl_place_holder_contents.json
  def create
    @tbl_place_holder_content = TblPlaceHolderContent.new(tbl_place_holder_content_params)

    respond_to do |format|
      if @tbl_place_holder_content.save
        format.html { redirect_to @tbl_place_holder_content, notice: 'Tbl place holder content was successfully created.' }
        format.json { render :show, status: :created, location: @tbl_place_holder_content }
      else
        format.html { render :new }
        format.json { render json: @tbl_place_holder_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tbl_place_holder_contents/1
  # PATCH/PUT /tbl_place_holder_contents/1.json
  def update
    respond_to do |format|
      if @tbl_place_holder_content.update(tbl_place_holder_content_params)
        format.html { redirect_to @tbl_place_holder_content, notice: 'Tbl place holder content was successfully updated.' }
        format.json { render :show, status: :ok, location: @tbl_place_holder_content }
      else
        format.html { render :edit }
        format.json { render json: @tbl_place_holder_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tbl_place_holder_contents/1
  # DELETE /tbl_place_holder_contents/1.json
  def destroy
    @tbl_place_holder_content.destroy
    respond_to do |format|
      format.html { redirect_to tbl_place_holder_contents_url, notice: 'Tbl place holder content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tbl_place_holder_content
      @tbl_place_holder_content = TblPlaceHolderContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tbl_place_holder_content_params
      params.require(:tbl_place_holder_content).permit(:PlaceHolderID, :ContentID)
    end
end

app/helpers/cms_helper.rb
module CmsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tbl_place_holder_contents_helper.rb
module TblPlaceHolderContentsHelper
end

app/helpers/vol_helper.rb
module VolHelper
end

app/views/tbl_place_holder_contents/_form.html.erb
<div class="external">
<%= form_for(@tbl_place_holder_content) do |f| %>
  <% if @tbl_place_holder_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tbl_place_holder_content.errors.count, "error") %> prohibited this tbl_place_holder_content from being saved:</h2>

      <ul>
      <% @tbl_place_holder_content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :PlaceHolderID %><br>
    <%= f.number_field :PlaceHolderID %>
  </div>
  <div class="field">
    <%= f.label :ContentID %><br>
    <%= f.number_field :ContentID %>
  </div>
  <div class="actions">
    <%= f.submit "Submit",:class => "btn_submit" %>
  </div>
<% end %>
</div>

app/views/tbl_place_holder_contents/edit.html.erb
<h1 class="edit1">Editing PlaceHolderContent</h1>

<%= render 'form' %>
<div class="edit2">
<%= link_to 'View', @tbl_place_holder_content, :class => "btn_submit" %> |
<%= link_to 'Back', tbl_place_holder_contents_path,:class => "btn_submit"%>
</div>

app/views/tbl_place_holder_contents/index.html.erb
<h1 class="index1">Place Holder Content Management</h1>
<div class="index3">
  <%= link_to 'Add New PlaceHolderContent', new_tbl_place_holder_content_path ,:class => "btn_submit"%>
</div>
<table class="index2">
  <thead>
    <tr>
      <th>Placeholderid</th>
      <th>Contentid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tbl_place_holder_contents.each do |tbl_place_holder_content| %>
      <tr>
        <td><%= tbl_place_holder_content.PlaceHolderID %></td>
        <td><%= tbl_place_holder_content.ContentID %></td>
        <td><%= link_to 'View', tbl_place_holder_content %></td>
        <td><%= link_to 'Edit', edit_tbl_place_holder_content_path(tbl_place_holder_content) %></td>
        <td><%= link_to 'Delete', tbl_place_holder_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tbl_place_holder_contents/new.html.erb
<h1 class="new1">Add New PlaceHolderContent</h1>

<%= render 'form' %>
<div class="new2">
<%= link_to 'Back', tbl_place_holder_contents_path, :class => "btn_submit" %>
</div>

app/views/tbl_place_holder_contents/show.html.erb
<div class="show2">
<p id="notice"><%= notice %></p>

<p>
  <strong>Placeholderid:</strong>
  <%= @tbl_place_holder_content.PlaceHolderID %>
</p>

<p>
  <strong>Contentid:</strong>
  <%= @tbl_place_holder_content.ContentID %>
</p>
</div>
<div class="show3">
<%= link_to 'Edit', edit_tbl_place_holder_content_path(@tbl_place_holder_content),:class => "btn_submit" %> |
<%= link_to 'Back', tbl_place_holder_contents_path, :class => "btn_submit" %>
</div>